services:
  postgres:
    image: postgres:15-alpine
    container_name: nethub_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nethub_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  migrate:
    image: migrate/migrate
    container_name: nethub_migrate
    volumes:
      - ./migrations:/migrations
    entrypoint:
      [
        "migrate",
        "-path",
        "/migrations",
        "-database",
        "postgresql://postgres:postgres@postgres:5432/postgres?sslmode=disable",
        "up"
      ]
    depends_on:
      - postgres

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: nethub_backend
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/postgres?sslmode=disable
      - HTTP_PORT=9000
      - ENV=production
    ports:
      - "9000:9000"
    depends_on:
      migrate:
        condition: service_completed_successfully

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: nethub_frontend
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  pgdata: