// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameAuditLog = "audit_logs"

// AuditLog mapped from table <audit_logs>
type AuditLog struct {
	ID         *string    `gorm:"column:id;type:object_id;primaryKey;default:gen_random_uuid()" json:"id"`
	Operation  *string    `gorm:"column:operation;type:text" json:"operation"`
	TableName_ *string    `gorm:"column:table_name;type:text" json:"table_name"`
	RecordID   *string    `gorm:"column:record_id;type:object_id" json:"record_id"`
	CreatedAt  *time.Time `gorm:"column:created_at;type:datetime;default:now()" json:"created_at"`
}

// TableName AuditLog's table name
func (*AuditLog) TableName() string {
	return TableNameAuditLog
}
