// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameDevice = "devices"

// Device mapped from table <devices>
type Device struct {
	ID           *string        `gorm:"column:id;type:object_id;primaryKey;default:gen_random_uuid()" json:"id"`
	CreatedAt    *time.Time     `gorm:"column:created_at;type:datetime;not null;default:now()" json:"created_at"`
	CreatedBy    *string        `gorm:"column:created_by;type:object_id" json:"created_by"`
	DeletedAt    gorm.DeletedAt `gorm:"column:deleted_at;type:datetime" json:"deleted_at"`
	Name         *string        `gorm:"column:name;type:text" json:"name"`
	UserID       *string        `gorm:"column:user_id;type:object_id" json:"user_id"`
	PlatformCode string         `gorm:"column:platform_code;type:code;not null" json:"platform_code"`
	IP           *string        `gorm:"column:ip;type:text" json:"ip"`
	Hostname     *string        `gorm:"column:hostname;type:text" json:"hostname"`
	Location     *string        `gorm:"column:location;type:object_id" json:"location"`
	IsActive     *bool          `gorm:"column:is_active;type:boolean;not null;default:true" json:"is_active"`
}

// TableName Device's table name
func (*Device) TableName() string {
	return TableNameDevice
}
