// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameLocation = "locations"

// Location mapped from table <locations>
type Location struct {
	ID         *string        `gorm:"column:id;type:object_id;primaryKey;default:gen_random_uuid()" json:"id"`
	CreatedAt  *time.Time     `gorm:"column:created_at;type:datetime;not null;default:now()" json:"created_at"`
	CreatedBy  *string        `gorm:"column:created_by;type:object_id" json:"created_by"`
	DeletedAt  gorm.DeletedAt `gorm:"column:deleted_at;type:datetime" json:"deleted_at"`
	Var        int64          `gorm:"column:var;type:bigint;not null" json:"var"`
	Name       *string        `gorm:"column:name;type:text" json:"name"`
	IsActive   *bool          `gorm:"column:is_active;type:boolean;not null;default:true" json:"is_active"`
	Coordinate *string        `gorm:"column:coordinate;type:coordinate" json:"coordinate"`
}

// TableName Location's table name
func (*Location) TableName() string {
	return TableNameLocation
}
