// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNamePlatform = "platforms"

// Platform mapped from table <platforms>
type Platform struct {
	ID        *string        `gorm:"column:id;type:object_id;primaryKey;default:gen_random_uuid()" json:"id"`
	CreatedAt *time.Time     `gorm:"column:created_at;type:datetime;not null;default:now()" json:"created_at"`
	Ver       int64          `gorm:"column:ver;type:bigint;not null" json:"ver"`
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at;type:datetime" json:"deleted_at"`
	Code      string         `gorm:"column:code;type:code;not null" json:"code"`
	Name      string         `gorm:"column:name;type:text;not null" json:"name"`
}

// TableName Platform's table name
func (*Platform) TableName() string {
	return TableNamePlatform
}
