// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameUser = "users"

// User mapped from table <users>
type User struct {
	ID             *string        `gorm:"column:id;type:object_id;primaryKey;default:gen_random_uuid()" json:"id"`
	CreatedAt      *time.Time     `gorm:"column:created_at;type:datetime;not null;default:now()" json:"created_at"`
	DeletedAt      gorm.DeletedAt `gorm:"column:deleted_at;type:datetime" json:"deleted_at"`
	CreatedBy      *string        `gorm:"column:created_by;type:object_id" json:"created_by"`
	Username       *string        `gorm:"column:username;type:text" json:"username"`
	Email          *string        `gorm:"column:email;type:text" json:"email"`
	LastName       *string        `gorm:"column:last_name;type:text" json:"last_name"`
	FirstName      *string        `gorm:"column:first_name;type:text" json:"first_name"`
	MiddleName     *string        `gorm:"column:middle_name;type:text" json:"middle_name"`
	BirthDate      *time.Time     `gorm:"column:birth_date;type:date" json:"birth_date"`
	AvatarFilePath *string        `gorm:"column:avatar_file_path;type:text" json:"avatar_file_path"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
