basePath: /
definitions:
  gorm.DeletedAt:
    properties:
      time:
        type: string
      valid:
        description: Valid is true if Time is not NULL
        type: boolean
    type: object
  nethub-mdm_internal_storage_model.Device:
    properties:
      created_at:
        type: string
      created_by:
        type: string
      deleted_at:
        $ref: '#/definitions/gorm.DeletedAt'
      hostname:
        type: string
      id:
        type: string
      ip:
        type: string
      is_active:
        type: boolean
      location:
        type: string
      name:
        type: string
      platform_code:
        type: string
      user_id:
        type: string
    type: object
  nethub-mdm_pkg_errors.ErrorResponse:
    properties:
      error:
        type: string
      message:
        type: string
    type: object
host: localhost:9000
info:
  contact: {}
  description: API сервера управления устройствами
  title: NetHub MDM API
  version: "1.0"
paths:
  /api/v1/devices:
    get:
      parameters:
      - description: Поиск по hostname
        in: query
        name: hostname
        type: string
      - description: Фильтр по активности
        in: query
        name: is_active
        type: boolean
      - default: 1
        description: Номер страницы
        in: query
        name: page
        type: integer
      - default: 10
        description: Количество на странице
        in: query
        name: limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Список устройств
      tags:
      - devices
    post:
      consumes:
      - application/json
      parameters:
      - description: Данные устройства
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/nethub-mdm_internal_storage_model.Device'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/nethub-mdm_internal_storage_model.Device'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/nethub-mdm_pkg_errors.ErrorResponse'
      summary: Создать устройство
      tags:
      - devices
  /api/v1/devices/{id}:
    delete:
      parameters:
      - description: ID устройства (UUID)
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: Успешно удалено (No Content)
        "400":
          description: Неверный ID
          schema:
            $ref: '#/definitions/nethub-mdm_pkg_errors.ErrorResponse'
        "500":
          description: Ошибка сервера
          schema:
            $ref: '#/definitions/nethub-mdm_pkg_errors.ErrorResponse'
      summary: Удалить устройство (Soft Delete)
      tags:
      - devices
    get:
      parameters:
      - description: ID устройства (UUID)
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/nethub-mdm_internal_storage_model.Device'
        "400":
          description: Неверный ID
          schema:
            $ref: '#/definitions/nethub-mdm_pkg_errors.ErrorResponse'
        "404":
          description: Устройство не найдено
          schema:
            $ref: '#/definitions/nethub-mdm_pkg_errors.ErrorResponse'
      summary: Получить устройство по ID
      tags:
      - devices
    put:
      consumes:
      - application/json
      parameters:
      - description: ID устройства (UUID)
        in: path
        name: id
        required: true
        type: string
      - description: Обновленные данные
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/nethub-mdm_internal_storage_model.Device'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/nethub-mdm_internal_storage_model.Device'
        "400":
          description: Неверный запрос
          schema:
            $ref: '#/definitions/nethub-mdm_pkg_errors.ErrorResponse'
        "500":
          description: Ошибка сервера
          schema:
            $ref: '#/definitions/nethub-mdm_pkg_errors.ErrorResponse'
      summary: Обновить устройство
      tags:
      - devices
swagger: "2.0"
